
package fromjava.server.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "addNumbers", targetNamespace = "http://server.fromjava/", wsdlLocation = "http://localhost:8080/Example_JAX_WS/IAddNumbers?wsdl")
public class AddNumbers_Service
    extends Service
{

    private final static URL ADDNUMBERS_WSDL_LOCATION;
    private final static WebServiceException ADDNUMBERS_EXCEPTION;
    private final static QName ADDNUMBERS_QNAME = new QName("http://server.fromjava/", "addNumbers");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Example_JAX_WS/IAddNumbers?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADDNUMBERS_WSDL_LOCATION = url;
        ADDNUMBERS_EXCEPTION = e;
    }

    public AddNumbers_Service() {
        super(__getWsdlLocation(), ADDNUMBERS_QNAME);
    }

    public AddNumbers_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADDNUMBERS_QNAME, features);
    }

    public AddNumbers_Service(URL wsdlLocation) {
        super(wsdlLocation, ADDNUMBERS_QNAME);
    }

    public AddNumbers_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADDNUMBERS_QNAME, features);
    }

    public AddNumbers_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddNumbers_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IAddNumbers
     */
    @WebEndpoint(name = "addNumberPort")
    public IAddNumbers getAddNumberPort() {
        return super.getPort(new QName("http://server.fromjava/", "addNumberPort"), IAddNumbers.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAddNumbers
     */
    @WebEndpoint(name = "addNumberPort")
    public IAddNumbers getAddNumberPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.fromjava/", "addNumberPort"), IAddNumbers.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADDNUMBERS_EXCEPTION!= null) {
            throw ADDNUMBERS_EXCEPTION;
        }
        return ADDNUMBERS_WSDL_LOCATION;
    }

}
